name: Publish release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Build, pack & publish - Xena
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish on version change - Xena.Core
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Xena/Xena.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
