name: Publish release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Build, pack & publish - Xena
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      # Publish
      - name: Build Xena soltion
        run: dotnet build Xena.sln
        
      - name: Publish NuGet packages to NuGet.org
        run: dotnet nuget push src/**/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
